---
# tasks file for apache_role
- name: Install Apache in RedHat-based OS
  become: true
  ansible.builtin.yum:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Apache in Debian-based OS
  become: true
  ansible.builtin.apt:
    name: apache2
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Start Apache in RedHat-based OS
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_facts['os_family'] == "RedHat"
  
- name: Start Apache in Debian-based OS
  become: true
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_facts['os_family'] == "Debian"

- name: Copy index.html
  become: true
  ansible.builtin.copy:
    src: ../static/index.html
    dest: /var/www/html/index.html

- name: Run smoke test
  ansible.builtin.uri:
    url: http://localhost
    return_content: yes
  register: result

- name: Debug smoke test
  ansible.builtin.debug:
    msg: "{{ result.content }}"